spring:
  profiles:
    active: localdev
telegram:
  bot-token: ${BOT_TOKEN}
  jokers:
    70098504:
      names:
        - Егор
        - Егорыч
      can-be-disliked: false
    305165616:
      names:
        - Дима
        - Дмитрий
        - Димон
    129119165:
      names:
        - Господин
        - Чувак
        - Владыка
        - Одмен
    123013760:
      names:
        - Иск
    458309789:
      can-be-disliked: false
      names:
        - Дима
        - Дмитрий
        - Димон
        - Димас
    70249892:
      names:
        - Саня
        - Соер
        - Александр
    230109600:
      names:
        - шакал
        - Девиан
        - Лёха
    215217027:
      names:
        - Олег
        - Олежа
